apiVersion: batch/v1
kind: Job
metadata:
  name: MYAPP
  namespace: default
  labels:
    app: MYAPP
spec:
  template:
    metadata:
      name: MYAPP
      labels:
        app: MYAPP
    spec:
      containers:
      - name: MYAPP
        image: python:3.7.6-alpine3.10
        command: ['sh', '-c', 'cd mnt && command']
        resources:
          requests:
            cpu: "1"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        env:
        - name: ENV_NAME
          value: ENV_VALUE
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: current-dir
          mountPath: /mnt
          subPath: ""
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: current-dir
        hostPath:
          path: /path/to/your/current/directory  # 替换为当前目录的绝对路径
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst