# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' act_local
#' 
#' act_local
#' @param yamlfile workflow files
#' @param arg args
#' @return yamlfile
#' 
#' @export
act_local <- function(yamlfile,arg = NULL){
  
  if (!file.exists(yamlfile)){
    stop("workflow file not found")
  }
  command <- glue::glue("act -W {yamlfile}")
  if (!is.null(arg)){
    command <- glue::glue("{command} {arg}")
  }
  
  system(command = command)
  return(yamlfile)
    
}
