# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' act_install
#' 
#' install act and run github action locally
#' @param system chr
#' @return NULL
#' 
#' @export
act_install <- function(system = c("linux","macos","windows")){
    if (system == "macos"){
      system("brew install act")
    }else if (system == "windows"){
      system("winget install nektos.act")
    }else{
      system("curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash")
    }
}
