# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' docker_install
#' 
#' install docker in linux systems
#' @param system linux,macos,windows
#' @return null
#' 
#' @export
docker_install <- function(system){
  if (system == "linux"){
    message("Note,install docker for linux servers")
  system("sudo wget -qO- https://github.com/rainoffallingstar/beaverdown/blob/main/dev/docker_install.sh | bash
")
  }else if(system == "macos"){
    system("brew install docker docker-compose")
  }else{
    system("winget install Docker.DockerDesktop")
  }
  
}
