# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_apply
#' 
#' kubectl_apply functions
#' @param yamlfiles chr
#' @param namespace chr,default as NULL
#' @return yamlfiles
#' 
#' @export
kubectl_apply <- function(yamlfiles,namespace = NULL){
    if (!file.exists(yamlfiles)) stop("the yamlfiles not found")
  command = glue::glue("kubectl apply -f {yamlfiles}")
  if (!is.null(namespace)) command = glue::glue("{command} -n {namespace}")
  message(glue::glue("RUN for {command}"))
  system(command)
  return(yamlfiles)
}
