# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_exec
#' 
#' kubectl exec wrapper 
#' @param podname podnames
#' @param arg_command the command to be ran
#' @return NULL
#' 
#' @export
kubectl_exec <- function(podname,
                         arg_command){
    command <- glue::glue("kubectl exec -it {podname} /bin/bash {arg_command} ")
    message(glue::glue("RUN for {command}"))
  system(command)
  return(podname)
}
