# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_get
#' 
#' kubectl_get functions for 
#'  deployments,service,ingress,namespaces,configmap,jobs,
#'  cronjob,secret,endpoints
#' @param servicetype chr,one of the following:deployments,service,ingress,namespaces,configmap,jobs, cronjob,secret,endpoints
#' @return data.frame
#' 
#' @export
kubectl_get <- function(servicetype){
  if (servicetype %in% c('deployments','service','ingress','namespaces','configmap','jobs', 'cronjob','secret','endpoints')){
    command <- glue::glue("kubectl get {servicetype}")
    if (servicetype == "configmap") command = paste(command,"--all-namespaces")
    message(glue::glue("RUN for {command}"))
  data <- system(command,intern = T) %>%
    {
  output <- .
  header <- output[1]
  data_lines <- output[-1]
  data <- do.call(rbind, lapply(data_lines, function(x) {
    strsplit(x, "\\s{2,}")[[1]]
  }))
  header_clean <- strsplit(header, "\\s{2,}")[[1]]
  if (ncol(data) == length(header_clean)) {
    colnames(data) <- header_clean
    data <- as.data.frame(data)
  }
    }
  return(data)
  }else {
    stop("choose the right function to be get inside one of the following:deployments,service,ingress,namespaces,configmap,jobs, cronjob,secret,endpoints")
  }
    
}
