# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_install
#' 
#' install kubectl in linux
#' @param system linux,macos,windows
#' @return null
#' 
#' @export
kubectl_install <- function(system = c("linux","macos","windows")){
  if (system == "linux"){
    system("curl -LO 'https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl'  && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl ")
  } else if (system == "macos"){
    system("brew install kubectl
")
  } else if (system == "windows"){
    system("winget install -e --id Kubernetes.kubectl
")
  }
    
}
