# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_portforward
#' 
#' kubectl port-forward warpper
#' @param podname the podname
#' @param hostport the hostport
#' @param childport the childport for the containers
#' @return NULL
#' 
#' @export
kubectl_portforward <- function(podname,
                                hostport,
                                childport){
    command = glue::glue("kubectl port-forward {podname} {hostport}:{childport}")
    message(glue::glue("RUN for {command}"))
  system(command)
  return(podname)
}
