# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_delete
#' 
#' kubectl delete warpper
#' 
#' @param servicetype chr,one of the following:deployments,service,ingress,namespaces,configmap,jobs, cronjob,secret,endpoints
#' @param object the object to remove
#' @return chr
#' 
#' @export
kubectl_delete <- function(object,servicetype){
    if (grep(".yaml",object)){
      if (!file.exists(object)) stop("the yamlfile not found")
      command <- glue::glue("kubectl delete -f {object}")
    } else {
      if (!(servicetype %in% c('deployments','service','ingress','namespaces','configmap','jobs', 'cronjob','secret','endpoints'))) stop("choose the right function to be get inside one of the following:deployments,service,ingress,namespaces,configmap,jobs, cronjob,secret,endpoints")
      command <- glue::glue("kubectl delete {servicetype} {object}")
    }
  message(glue::glue("RUN for {command}"))
  system(command)
  return(object)
}
