# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' kubectl_logs
#' 
#' kubectl logs wrapper 
#' @param podname the podname
#' @return NULL
#' 
#' @export
kubectl_logs <- function(podname){
    command <- glue::glue("kubectl logs --follow {podname}")
    message(glue::glue("RUN for {command}"))
  system(command)
  return(podname)
}
