# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' minikube_install
#' 
#' install minikube
#' @param system linux,macos,windows
#' @return null
#' 
#' @export
minikube_install <- function(system = c("linux","macos","windows")){
  if (system == "linux"){
    message("Note,install minikube for linux servers")
  system("sudo wget -qO- https://github.com/rainoffallingstar/beaverdown/blob/main/dev/minikube_install.sh | bash
")
  }else if (system == "macos"){
  system("brew install minikube")
  } else {
  system("winget install Kubernetes.minikube")
}
  
}
