# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' minikube_start
#' 
#' start a cluster by minikube
#' 
#' @return null
#' 
#' @export
minikube_start <- function(){
    system("minikube start")
}
