# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' placeholder
#' 
#' creat a dir that is not empty
#' @param path char,a dir to be make
#' @return path
#' 
#' @export
#' @examples
#' placeholder("testtemp")
#' fs::dir_delete("testtemp")
placeholder <- function(path){
    fs::dir_create(path = path)
  writeLines("",con = paste0(path,"/place.holder"))
  return(path)
}
