# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' submit_job
#' 
#' submit_job and run
#' @param task_names the name of the submit job
#' @param namespace the namespace used 
#' @param container the container used
#' @param command the command submit to run
#' @param ncpu the cpu request
#' @param nram the memory request
#' @param cpu_limit the limit cpu
#' @param nram_limit the nram limit
#' @param env_list the env value list,default as NULL
#' @param restartPolicy the restartPolicy,default as Never
#' @return NULL
#' 
#' @export
submit_job <- function(task_names,
                       namespace = "default",
                       container,
                       command,
                       ncpu = 8,
                       nram = "1024Mi",
                       cpu_limit = 100,
                       nram_limit = "10240000Mi",
                       env_list = NULL,
                       hostPath = getwd(),
                       restartPolicy = "Never"){
    job_yaml = job_yaml
    # namespace 
    job_yaml$metadata$namespace <- namespace
    # task_names
    job_yaml$metadata$name <- task_names
    job_yaml$metadata$labels$app <- task_names
    job_yaml$spec$template$metadata$name <- task_names
    job_yaml$spec$template$metadata$labels$app <- task_names
    job_yaml$spec$template$spec$containers[[1]]$name <- task_names
    # containers
    job_yaml$spec$template$spec$containers[[1]]$image <- container 
    # command 
    job_yaml$spec$template$spec$containers[[1]]$command <- stringr::str_replace(job_yaml$spec$template$spec$containers[[1]]$command,"command",command)
    # resources_request
    # cpu
    job_yaml$spec$template$spec$containers[[1]]$resources$requests$cpu <- ncpu
    #memory
    job_yaml$spec$template$spec$containers[[1]]$resources$requests$memory <- nram
    # resources_limit 
    # cpu
    job_yaml$spec$template$spec$containers[[1]]$resources$limits$cpu <- cpu_limit
    #memory
    job_yaml$spec$template$spec$containers[[1]]$resources$limits$memory <- nram_limit
    # env
    if (!is.null(env_list))job_yaml$spec$template$spec$containers[[1]]$env <- env_list
    #volumes(current dir)
    job_yaml$spec$template$spec$volumes[[2]]$hostPath <- hostPath
    # restart #job_yaml$spec$template$spec$dnsPolicy
    job_yaml$spec$template$spec$restartPolicy <- restartPolicy
    fs::dir_create(paste0(
      hostPath,"/result/yaml/"
    ))
    yamlfile <- paste0("result/yaml/",task_names,".yaml")
    yaml::write_yaml(job_yaml,file = yamlfile )
    message("runs the yamlfile")
    kubectl_apply(yamlfiles = yamlfiles,
                  namespace = namespace)
    return(task_names)
}
